export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAILURE = "ADD_ARTICLE_FAILURE";
export const ADD_ARTICLE_STARTED = "ADD_ARTICLE_STARTED";
export const DELETE_ARTICLE = "DELETE_ARTICLE";